[package]
name = "ntru"
version = "0.1.0"
edition = "2021"

[dependencies]
hybrid-array = { path="../../hybrid-array", features = ["extra-sizes"] }
rand_core = "0.6.4"
sha2 = "0.10.8"

[dev-dependencies]
rayon="1.10.0"
